### ISSUE TITLE
Failed to compile: clang: error: invalid linker name in argument '-fuse-ld=mold'

### ISSUE THREAD

**Issue by JhonnyRice** [ZeroX-DG/moon#127]
System: Ubuntu 21.04
Kernel: Linux 5.15.0-46-generic
Rust version: rustc 1.62.0

This error happens to most of the crates it tries to compile.

**Comment by ZeroX-DG** [comment]
Ah yes. This is because moon uses the [`mold`](https://github.com/rui314/mold) linker so you need to install it first before compiling:
```
sudo apt intall mold
```
Let me know if you still having trouble with this.

**Comment by JhonnyRice** [comment]
no problem! compiled without errors
